FROM mongo:6.0

# Set environment variables for user authentication
ENV MONGO_INITDB_ROOT_USERNAME=admin
ENV MONGO_INITDB_ROOT_PASSWORD=password

# Optional: Expose MongoDB default port
EXPOSE 27017

# Optional: Add a volume for data persistence
VOLUME /data/db
